### PR TITLE
For some reason take_screenshot returns nil for the file object in fo…

### PR DESCRIPTION
**Pull request by Blackbaud-KyleMartinez**
…r cst.tr.uploads.survey_upload_without_overwrite. Adding a nil check before embeding

### CODE REVIEW

**Comment by Blackbaud-TitusFortner** [comment]
What is getting passed in to HookHelper.take_screenshot ? Is this something we should be fixing there?

**Comment by titusfortner** [comment]
This could have to do with Cucumber 2 changes.  #46 might fix this as well

**Comment by Blackbaud-KyleMartinez** [comment]
I think your right. I'll verify that your change in #46 fixes my problem once you merge it in and then I will close this pull request

**Comment by Blackbaud-TitusFortner** [comment]
This may be fixed by PR #46

**Pull request closed without merging**
